name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create file google_services.json
      run: cat /home/runner/work/lexi-app/lexi-app/app/google-services.json | base64
    - name: Putting data google
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES }}
      run: echo $DATA | base64 -d > /home/runner/work/lexi-app/lexi-app/app/google-services.json
    - name: Create file Secrets.kt
      run: touch ./app/src/main/java/com/example/lexiapp/domain/model/Secrets.kt
    - name: Putting data secrets
      env:
        DATA: ${{ secrets.SECRETS_KT }}
      run: echo $DATA | base64 -d > ./app/src/main/java/com/example/lexiapp/domain/model/Secrets.kt
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
